### ISSUE TITLE
White space around figure

### ISSUE THREAD

**Issue by guidomeijer** [dougollerenshaw/figrid#10]
Thanks for making this useful package! I have a problem, when I make a plot it doesn't fill the entire figure. I get a white border around it, especially on the left and top.

Code:
```
fig = plt.figure(figsize=(7, 9), dpi=DPI)  
ax = {'panel_A': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0, 0.18]),
      'panel_B': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0.25, 0.5],
                                       dim=[1, n_columns + 1], wspace=0.3),
      'panel_C': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0.55, 0.8],
                                       dim=[1, n_columns + 1], wspace=0.3),
      'panel_D': fg.place_axes_on_grid(fig, xspan=[0.2, 0.45], yspan=[0.85, 1]),
      'panel_E': fg.place_axes_on_grid(fig, xspan=[0.55, 1], yspan=[0.85, 1])}

# Add subplot labels
labels = [{'label_text':'a', 'xpos':0, 'ypos':0, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'b', 'xpos':0, 'ypos':0.2, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'c', 'xpos':0, 'ypos':0.55, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'d', 'xpos':0, 'ypos':0.85, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'e', 'xpos':0.5, 'ypos':0.85, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'}]
fg.add_labels(fig, labels)
```
As you can see here (hopefully) the figure doesn't start at the top left:
  
![Figure_1](https://user-images.githubusercontent.com/19360723/150151028-0b0ec92c-842b-4d7e-bb9e-24371d89417b.jpeg)

**Comment by dougollerenshaw** [comment]
@guidomeijer when you save your figure to disk, try passing the `bbox_inches='tight'` keyword argument to `fig.savefig`. When I save the figure without that argument, I can replicate the whitespace you're seeing. With that argument, the margins are removed.

Note that I don't see any margins when I display the figure in a Jupyter Notebook cell (with or without the `bbox_inches='tight'` keyword argument).

Full code to generate/save the figure to your home directory:

```python
import figrid as fg
import matplotlib.pyplot as plt
import os

DPI = 300
n_columns=3

fig = plt.figure(figsize=(7, 9), dpi=DPI)  
ax = {'panel_A': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0, 0.18]),
      'panel_B': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0.25, 0.5],
                                       dim=[1, n_columns + 1], wspace=0.3),
      'panel_C': fg.place_axes_on_grid(fig, xspan=[0.1, 1], yspan=[0.55, 0.8],
                                       dim=[1, n_columns + 1], wspace=0.3),
      'panel_D': fg.place_axes_on_grid(fig, xspan=[0.2, 0.45], yspan=[0.85, 1]),
      'panel_E': fg.place_axes_on_grid(fig, xspan=[0.55, 1], yspan=[0.85, 1])}

# Add subplot labels
labels = [{'label_text':'a', 'xpos':0, 'ypos':0, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'b', 'xpos':0, 'ypos':0.2, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'c', 'xpos':0, 'ypos':0.55, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'d', 'xpos':0, 'ypos':0.85, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'},
          {'label_text':'e', 'xpos':0.5, 'ypos':0.85, 'fontsize':10, 'weight': 'bold',
           'ha': 'right', 'va': 'bottom'}]
fg.add_labels(fig, labels)

fig.patch.set_facecolor('white')
fig.savefig(os.path.join(os.path.expanduser('~'), 'test_figure.png'), bbox_inches='tight')
```

**Comment by guidomeijer** [comment]
Thanks for getting back to me. I tried adding the `bbox_inches='tight'` argument but I get the following error:
```
Traceback (most recent call last):

  File "C:\Users\guido\AppData\Local\Temp/ipykernel_10220/841714944.py", line 1, in <module>
    plt.savefig(join(FIG_PATH, 'figure3.pdf'), pad_inches=0, bbox_inches='tight')

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\pyplot.py", line 966, in savefig
    res = fig.savefig(*args, **kwargs)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 78, in print_figure
    super().print_figure(*args, **kwargs)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\backend_bases.py", line 2234, in print_figure
    bbox_inches = self.figure.get_tightbbox(

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\figure.py", line 1639, in get_tightbbox
    bbox = a.get_tightbbox(renderer)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\axes\_base.py", line 4477, in get_tightbbox
    bbox = a.get_tightbbox(renderer)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\artist.py", line 306, in get_tightbbox
    bbox = self.get_window_extent(renderer)

  File "C:\Users\guido\anaconda3\envs\iblenv\lib\site-packages\matplotlib\image.py", line 913, in get_window_extent
    x0, x1, y0, y1 = self._extent

TypeError: cannot unpack non-iterable NoneType object
```

**Comment by dougollerenshaw** [comment]
I'm not sure what's going on there. that looks like a matplotlib issue, not something specific to this package (which just wraps matplotlib). I don't have access to a Windows computer so can't replicate, but the code block I pasted above works for me on Linux and Mac. 

For what it's worth, I'm on matplotlib version 3.5.1
```python
import matplotlib as mpl
print(mpl.__version__)
```

Maybe try troubleshooting using this simple code block (which also runs successfully for me):
```python
import matplotlib.pyplot as plt
import os
fig, ax = plt.subplots(figsize=(8.5,11))
FIG_PATH = os.path.join(os.path.expanduser('~'), 'test_figure_2.png')
fig.savefig(FIG_PATH, pad_inches=0, bbox_inches='tight')
```

**Comment by dougollerenshaw** [comment]
@guidomeijer since I don't think this is a package-specific issue, I'm going to mark this as closed. If you do figure out what was going wrong for you, please followup here in case anyone else runs into the same.

**Comment by guidomeijer** [comment]
Sounds good, it's definitely a matplotlib issue. It works fine without any plots in it but after I put in the plots I get this error, both on Windows and Linux. I'll drop a line here if I ever find out what's causing it.
